menu:
    Blog: /
    Archive: /archives/
    Tags: /tags/
    # Weibo: http://weibo.com/sunchongsheng
    GitHub: https://github.com/yytdfc
    About: /about/
    # Rss: /atom.xml

favicon: /images/favicon.png
logo: /images/logo.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:
cloudTie: b710aea8146b4b82be4291d960552145

# Analytics
# google-analytics:
# ga: UA-65933410-1

busuanzicount: true

# Copyright Infomation
startyear: 2016
